#!/usr/bin/env python3
"""tools/build.py — the whole build system. Standard library only.

    python3 tools/build.py          rebuild every root .html from src/
    python3 tools/build.py --check  rebuild in memory and diff against disk;
                                    prints a unified diff and exits 1 if stale

Three constructs, and no more. Do not add a fourth.

  1. <!--@ ... @-->   front matter at the top of a page source.
                      "key: value", or "key: <<" ... "<<" for multi-line.
  2. <!-- include: name.html -->   on a line by itself. The directive consumes
                      its own line, and the partial carries its own final
                      indentation, so an include contributes none.
  3. {{ key }}        page scope over site scope. Defined -> the value, even if
                      empty. Undefined -> <span class="placeholder">[KEY]</span>,
                      which is how a to-be-confirmed value renders.

There are no loops, no conditionals and no slots, deliberately. If you need a
conditional, add a second partial or a variable group in src/site.vars.
"""

import re
import sys
import difflib
from pathlib import Path

ROOT     = Path(__file__).resolve().parent.parent
SRC      = ROOT / 'src'
PAGES    = SRC / 'pages'
PARTIALS = SRC / 'partials'

FRONT   = re.compile(r'\A<!--@\n(.*?)\n@-->\n', re.S)
INCLUDE = re.compile(r'^[ \t]*<!-- include:\s*(\S+?)\s*-->[ \t]*\n', re.M)
VAR     = re.compile(r'\{\{\s*([A-Za-z0-9_.]+)\s*\}\}')


def parse_vars(text, where):
    """key: value | key: << ...block... << | [group] namespace headers."""
    out, ns = {}, ''
    lines = text.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i]
        i += 1
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        if s.startswith('[') and s.endswith(']'):
            ns = s[1:-1] + '.'
            continue
        key, sep, val = line.partition(':')
        if not sep:
            raise SystemExit(f'{where}: cannot parse line: {line!r}')
        key, val = ns + key.strip(), val.strip()
        if val == '<<':
            buf = []
            while i < len(lines) and lines[i].strip() != '<<':
                buf.append(lines[i])
                i += 1
            if i >= len(lines):
                raise SystemExit(f'{where}: unterminated << block for {key!r}')
            i += 1
            val = '\n'.join(buf)
        out[key] = val
    return out


def expand_includes(text, depth=0):
    if depth > 8:
        raise SystemExit('include nested more than 8 deep — probably a loop')

    def swap(m):
        p = PARTIALS / m.group(1)
        if not p.is_file():
            raise SystemExit(f'no such partial: src/partials/{m.group(1)}')
        return expand_includes(p.read_text(encoding='utf-8'), depth + 1)

    return INCLUDE.sub(swap, text)


def substitute(text, scope):
    """Repeat until stable: a variable's value may itself contain {{ ... }}."""
    for _ in range(6):
        new = VAR.sub(
            lambda m: scope[m.group(1)] if m.group(1) in scope
            else f'<span class="placeholder">[{m.group(1).upper()}]</span>',
            text)
        if new == text:
            return new
        text = new
    raise SystemExit('variable substitution did not settle — check for a cycle')


def build():
    site = parse_vars((SRC / 'site.vars').read_text(encoding='utf-8'), 'site.vars')
    out, sitemap = {}, []

    for src in sorted(PAGES.glob('*.html')):
        raw = src.read_text(encoding='utf-8')
        m = FRONT.match(raw)
        if not m:
            raise SystemExit(f'{src.name}: no <!--@ ... @--> front matter')
        fm = parse_vars(m.group(1), src.name)

        scope = {k: v for k, v in site.items() if '.' not in k}
        for g in (g.strip() for g in fm.pop('use', '').split(',') if g.strip()):
            hits = {k[len(g) + 1:]: v for k, v in site.items()
                    if k.startswith(g + '.')}
            if not hits:
                raise SystemExit(f'{src.name}: no [{g}] group in site.vars')
            scope.update(hits)
        scope.update(fm)

        # Derived, so the canonical URL, og:url and the breadcrumb cannot drift.
        slug = scope.get('slug', '')
        scope.setdefault('canonical', f"{scope['site_url']}/{slug}".rstrip('/') if slug
                         else f"{scope['site_url']}/")
        scope.setdefault('og_title', scope.get('title', ''))

        page = substitute(expand_includes(raw[m.end():]), scope)
        out[fm.get('out', src.name)] = banner(page, src.name)
        sitemap.append((scope.get('sitemap', ''), scope['canonical']))

    out['sitemap.xml'] = build_sitemap(sitemap)
    return out


BANNER = """<!--
  GENERATED by tools/build.py from src/pages/{src}
  DO NOT EDIT THIS FILE. Your change will be overwritten by the next build.

  Page copy and page-specific markup   ->  src/pages/{src}
  Nav, footer, quote form, head block  ->  src/partials/
  Phone number, booking URL, TBD values ->  src/site.vars

  Then run:  python3 tools/build.py
-->
"""


def banner(page, src_name):
    """Put the notice straight after the DOCTYPE, where it is the first
    thing anyone opening the file reads."""
    marker = '<!DOCTYPE html>\n'
    if not page.startswith(marker):
        return page
    return marker + BANNER.format(src=src_name) + page[len(marker):]


SITEMAP_HEAD = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by tools/build.py from the `slug` and `sitemap` keys in
  src/pages/*.html. Do not edit: run `python3 tools/build.py` instead.

  Each <loc> is the same derived value as that page's own
  <link rel="canonical">, so the two cannot drift apart.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
'''


def build_sitemap(rows):
    """Highest priority first, then alphabetical — order is not significant
    to a crawler, so this just keeps the file stable between builds."""
    entries = []
    for meta, loc in rows:
        if not meta:
            continue
        changefreq, priority = meta.split()
        entries.append((-float(priority), loc, changefreq, priority))
    body = ''.join(
        f'\n  <url>\n    <loc>{loc}</loc>\n'
        f'    <changefreq>{cf}</changefreq>\n'
        f'    <priority>{pr}</priority>\n  </url>\n'
        for _, loc, cf, pr in sorted(entries))
    return SITEMAP_HEAD + body + '\n</urlset>\n'


def main():
    check = '--check' in sys.argv[1:]
    pages = build()
    stale = []

    for name, text in sorted(pages.items()):
        dest = ROOT / name
        current = dest.read_text(encoding='utf-8') if dest.is_file() else None
        if current == text:
            continue
        stale.append(name)
        if check:
            print(''.join(difflib.unified_diff(
                (current or '').splitlines(keepends=True),
                text.splitlines(keepends=True),
                fromfile=f'{name} (on disk)', tofile=f'{name} (from src/)')), end='')
        else:
            dest.write_text(text, encoding='utf-8', newline='\n')

    if check:
        if stale:
            print(f'\n{len(stale)} page(s) out of date: {", ".join(stale)}')
            print('Run: python3 tools/build.py')
            return 1
        print(f'{len(pages)} page(s) up to date.')
        return 0

    print(f'built {len(pages)} page(s); {len(stale)} written, '
          f'{len(pages) - len(stale)} already current.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
